"""GATE 17 — dependency/supply-chain audit.

Two modes:
  python tools/dependency_audit.py --audit
      Runs `pip check` and `pip-audit` live (needs network for the OSV
      database), captures the environment, and writes
      certification/DEPENDENCY_AUDIT.md.
  python tools/dependency_audit.py --check   (used by the test suite)
      Verifies the committed artifact lists the same direct dependencies
      as runtime/pyproject.toml (drift check). Does not touch the network.

The artifact separates three groups explicitly:
  - project dependencies: what the runtime ships (pyproject dependencies);
  - test dependencies: the [project.optional-dependencies] test extra;
  - toolchain: pip-audit itself, pip, and anything else in the scan
    environment that is neither. Findings (if any) are attributed to the
    group they belong to, so a toolchain CVE can never be mistaken for a
    project CVE.
"""
from __future__ import annotations

import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent  # repo root
RUNTIME = ROOT / "runtime"
ARTIFACT = ROOT / "certification" / "DEPENDENCY_AUDIT.md"

PY = sys.executable


def _run(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(args, capture_output=True, text=True, timeout=300)


def _direct_deps() -> tuple[list[str], list[str]]:
    import tomllib
    data = tomllib.loads((RUNTIME / "pyproject.toml").read_text())
    proj = data["project"]["dependencies"]
    test = data["project"]["optional-dependencies"]["test"]
    return proj, test


def _name(spec: str) -> str:
    return spec.split(";")[0].split("[")[0].strip().split(">=")[0] \
        .split("<")[0].split("==")[0].split("~=")[0].lower().replace("-", "_")


def _installed() -> dict[str, str]:
    out: dict[str, str] = {}
    r = _run(PY, "-m", "pip", "freeze")
    for line in r.stdout.splitlines():
        line = line.strip()
        if not line or line.startswith("-e ") or "://" in line:
            continue
        if "==" in line:
            name, ver = line.split("==", 1)
            out[name.lower().replace("-", "_")] = ver
    return out


def _do_audit() -> int:
    proj_specs, test_specs = _direct_deps()
    proj_names = {_name(s) for s in proj_specs}
    test_names = {_name(s) for s in test_specs}
    installed = _installed()

    check = _run(PY, "-m", "pip", "check")
    audit = _run(PY, "-m", "pip_audit", "--desc", "--format=json")
    pa_ver = _run(PY, "-m", "pip_audit", "--version").stdout.strip()

    vulns: list[dict] = []
    scanned = 0
    if audit.returncode in (0, 1):
        data = json.loads(audit.stdout or "{}")
        deps = data.get("dependencies", [])
        scanned = len(deps)
        for dep in deps:
            for v in dep.get("vulns", []):
                vulns.append({
                    "package": dep["name"], "version": dep["version"],
                    "id": v["id"],
                    "aliases": v.get("aliases", []),
                    "summary": (v.get("details") or "")[:200],
                })
    else:
        print("pip-audit failed:\n" + audit.stderr[-2000:])
        return 1

    def group(name: str) -> str:
        key = name.lower().replace("-", "_")
        if key in proj_names or key == "muse_skill_hub_runtime":
            return "project"
        if key in test_names:
            return "test"
        return "toolchain"

    by_group: dict[str, list[str]] = {"project": [], "test": [],
                                      "toolchain": []}
    for name in sorted(installed):
        by_group[group(name)].append(f"{name}=={installed[name]}")

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "<!-- AUDIT:START -->",
        "_Generated by `runtime/tools/dependency_audit.py --audit` — "
        "re-run to refresh; do not hand-edit._",
        "",
        f"**Date:** {now} · **pip-audit:** {pa_ver} · "
        f"**pip check:** {'clean' if check.returncode == 0 else 'FAILED'}",
        "",
        "## Result",
        "",
        f"**{len(vulns)} known vulnerabilities** across {scanned} scanned "
        "packages (OSV database).",
        "",
    ]
    if vulns:
        for group_name in ("project", "test", "toolchain"):
            gv = [v for v in vulns
                  if group(v["package"]) == group_name]
            lines.append(f"### {group_name} findings: {len(gv)}")
            for v in gv:
                lines += [
                    f"- **{v['package']} {v['version']}** — {v['id']}",
                    f"  aliases: {', '.join(v['aliases']) or 'none'}",
                    f"  {v['summary']}",
                ]
            lines.append("")
    else:
        lines += [
            "No findings in any group: project dependencies, test "
            "dependencies, and toolchain are all clear.",
            "",
        ]
    lines += [
        "## Scanned environment (grouped)",
        "",
        "### project dependencies (what the runtime ships)",
        "",
        *[f"- `{p}`" for p in by_group["project"]],
        "",
        "pyproject declares:",
        *[f"- `{s}`" for s in proj_specs],
        "",
        "### test dependencies",
        "",
        *[f"- `{p}`" for p in by_group["test"]],
        "",
        "### toolchain (audit tooling and installer — not shipped)",
        "",
        *[f"- `{p}`" for p in by_group["toolchain"]],
        "",
        "## Notes",
        "",
        "- `pip check` reports no broken requirements.",
        "- The wheel ships only the `project` group; `test` and `toolchain` "
        "never reach users.",
        "- Re-run this audit before every release; the `--check` test fails "
        "if the artifact drifts from pyproject.",
        "<!-- AUDIT:END -->",
    ]
    ARTIFACT.parent.mkdir(parents=True, exist_ok=True)
    ARTIFACT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {ARTIFACT}: {len(vulns)} vulns / {scanned} packages")
    return 0


def _do_check() -> int:
    proj_specs, _ = _direct_deps()
    declared = {_name(s) for s in proj_specs}
    text = ARTIFACT.read_text(encoding="utf-8") if ARTIFACT.exists() else ""
    if "<!-- AUDIT:START -->" not in text or "<!-- AUDIT:END -->" not in text:
        print("OUT OF SYNC: dependency audit artifact missing or truncated")
        return 1
    missing = [s for s in proj_specs if f"`{s}`" not in text]
    if missing:
        print("OUT OF SYNC: artifact missing declared deps: "
              + ", ".join(missing))
        print("re-run: python tools/dependency_audit.py --audit")
        return 1
    print(f"dependency audit in sync ({len(declared)} direct deps listed)")
    return 0


def main() -> int:
    if "--audit" in sys.argv:
        return _do_audit()
    return _do_check()


if __name__ == "__main__":
    sys.exit(main())
