"""GATE 18 — performance sanity: measurements only, no guarantees.

Measures wall-clock time for the runtime's hot paths on THIS machine and
writes certification/PERF_SANITY.md. These numbers are observations, not
SLAs: they depend on hardware, disk, and OS, and the project makes no
latency promises. The value of this gate is (a) proving nothing is
pathologically slow, and (b) giving future work a baseline to compare
against.

Modes:
  python tools/perf_sanity.py --measure   run benchmarks, write artifact
  python tools/perf_sanity.py --check      verify the artifact lists every
                                          measured operation (drift check;
                                          does not compare timings)
"""
from __future__ import annotations

import asyncio
import os
import platform
import statistics
import sys
import tempfile
import time
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
RUNTIME = ROOT / "runtime"
ARTIFACT = ROOT / "certification" / "PERF_SANITY.md"

sys.path.insert(0, str(RUNTIME))


def _timeit(fn, rounds: int = 20) -> tuple[float, float]:
    samples = []
    for _ in range(rounds):
        start = time.perf_counter()
        fn()
        samples.append((time.perf_counter() - start) * 1000)
    return statistics.median(samples), max(samples)


def _timeit_async(coro_fn, rounds: int = 20) -> tuple[float, float]:
    def run():
        asyncio.run(coro_fn())
    return _timeit(run, rounds)


# Each entry: (operation name, callable). Set up once in main().
OPERATIONS: list[tuple[str, object]] = []


def measure() -> dict[str, tuple[float, float]]:
    from skillhub import approval as approval_mod
    from skillhub import audit as audit_mod
    from skillhub import mock as mock_harness
    from skillhub.registry import (dispatch, load_registry, mcp_tools,
                                   _idem_commit, _idem_release,
                                   _idem_reserve, _params_hash)

    tmp = tempfile.mkdtemp(prefix="perf-")
    os.environ["SKILLHUB_LOCAL_DIR"] = tmp
    os.environ["GITHUB_TOKEN"] = "mock"
    mock_harness.enable()

    async def ok_responder(method, url, **kw):
        return {"items": []}
    mock_harness.register("github", ok_responder)

    reg = load_registry()
    entry = reg["github"]

    results: dict[str, tuple[float, float]] = {}

    results["registry load (97 skills, 96 drivers)"] = _timeit(
        load_registry, rounds=5)
    results["mcp tool list build (222 tools)"] = _timeit(
        lambda: mcp_tools(reg), rounds=10)

    async def do_dispatch():
        await dispatch(entry, "search_repositories", {"query": "perf"})
    results["dispatch read action (mock, incl. audit)"] = _timeit_async(
        do_dispatch)

    def approval_cycle():
        item = approval_mod.request_approval(
            "perfskill", "do_thing", {"x": 1}, risk="write")
        approval_mod.approve(item["approval_id"])
        approval_mod.consume(item["approval_id"], "perfskill", "do_thing",
                            {"x": 1}, risk="write")
    results["approval request+approve+consume"] = _timeit(approval_cycle)

    results["audit log append"] = _timeit(
        lambda: audit_mod.log({"skill": "perf", "action": "x",
                               "result": "success"}))

    def idem_cycle():
        key = f"perf-{time.monotonic_ns()}"
        owned, _ = _idem_reserve(key, "s", "a", _params_hash({"x": 1}))
        assert owned
        _idem_commit(key, {"ok": True})
        _idem_release(key)
    results["idempotency reserve+commit+release"] = _timeit(idem_cycle)

    from skillhub import credentials as creds_mod
    results["credential resolution"] = _timeit(
        lambda: creds_mod.resolve_credential("GITHUB_TOKEN", "github"),
        rounds=50)

    mock_harness.reset()
    return results


def _machine() -> str:
    try:
        cpu = Path("/proc/cpuinfo").read_text().split("model name")[1] \
            .split(":")[1].split("\n")[0].strip()
    except Exception:
        cpu = platform.processor() or "unknown"
    return (f"{platform.system()} {platform.release()} · "
            f"{platform.machine()} · {cpu} · "
            f"python {platform.python_version()}")


def _do_measure() -> int:
    results = measure()
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "<!-- PERF:START -->",
        "_Generated by `runtime/tools/perf_sanity.py --measure` — "
        "measurements only, not guarantees. Re-run to refresh; do not "
        "hand-edit._",
        "",
        f"**Date:** {now} · **Machine:** {_machine()}",
        "",
        "> These are wall-clock observations on one machine. The project "
        "makes no latency promises; provider network calls dominate real "
        "dispatch time and are outside the runtime's control. The numbers "
        "exist to catch pathological slowdowns and to give future work a "
        "baseline.",
        "",
        "| operation | median | max |",
        "|---|---|---|",
    ]
    for name, (median, mx) in results.items():
        fmt = (lambda v: f"{v:.3f} ms") if median < 0.1 \
            else (lambda v: f"{v:.2f} ms")
        lines.append(f"| {name} | {fmt(median)} | {fmt(mx)} |")
    lines += [
        "",
        "## Notes",
        "",
        "- `dispatch` is measured against the mock harness: no network, so "
        "this is pure runtime overhead (validation, approval check, "
        "credential resolution, idempotency, audit, output validation).",
        "- `registry load` parses all 97 SKILL manifests and builds 210 MCP "
        "tool schemas; it happens once per process start.",
        "- The full test suite (258 tests incl. 20-process race tests) runs "
        "in ~85 s on this machine.",
        "<!-- PERF:END -->",
    ]
    ARTIFACT.parent.mkdir(parents=True, exist_ok=True)
    ARTIFACT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {ARTIFACT} ({len(results)} operations)")
    return 0


def _do_check() -> int:
    text = ARTIFACT.read_text(encoding="utf-8") if ARTIFACT.exists() else ""
    if "<!-- PERF:START -->" not in text or "<!-- PERF:END -->" not in text:
        print("OUT OF SYNC: perf artifact missing or truncated")
        return 1
    expected = ["registry load", "mcp tool list build", "dispatch read action",
                "approval request+approve+consume", "audit log append",
                "idempotency reserve+commit+release", "credential resolution"]
    missing = [op for op in expected if op not in text]
    if missing:
        print("OUT OF SYNC: artifact missing operations: "
              + ", ".join(missing))
        print("re-run: python tools/perf_sanity.py --measure")
        return 1
    if "not guarantees" not in text:
        print("OUT OF SYNC: artifact must disclaim guarantees")
        return 1
    print(f"perf artifact in sync ({len(expected)} operations listed)")
    return 0


def main() -> int:
    if "--measure" in sys.argv:
        return _do_measure()
    return _do_check()


if __name__ == "__main__":
    sys.exit(main())
