"""Generate the provider contract matrix (GATE 15).

Evidence tiers are determined from ground truth, not from docs:

- ``live``: a test performs a REAL network call to the provider's
  servers (keyless public APIs). The (skill -> test function) mapping is
  explicit and the generator asserts each test function still exists —
  a renamed/deleted live test can never silently keep its tier.
- ``mock-contract``: a mock-harness contract test registers a responder
  for the skill and asserts request shape + response parsing
  (detected by scanning the test suite for
  ``mock_harness.register("<skill>", ...)``).
- ``structural``: everything else — schema/dispatch/unit tests only,
  never touched a provider server.

Output: ``certification/PROVIDER_MATRIX.md`` (generated — do not hand-edit).

Usage:  python tools/provider_matrix.py [--check]
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent  # repo root
RUNTIME = ROOT / "runtime"
MATRIX_PATH = ROOT / "certification" / "PROVIDER_MATRIX.md"

# skill -> test function that performs a REAL provider call.
# Human-verified: these tests hit the provider's servers over the network.
LIVE_TESTS: dict[str, str] = {
    "github": "test_github_search_executes_real_api_call",   # api.github.com
    "podcast": "test_podcast_search_live",                   # iTunes Search API
}

# skill -> test functions that assert the driver's request shape and
# response parsing against a mocked transport (no provider contact).
# Human-verified: these tests exercise the real driver code unmodified.
# v2.3: lovable/replit upgraded from stubs to real drivers; their
# contract tests prove correct API requests and plan/Enterprise-gate
# error translation.
MOCK_CONTRACT_TESTS: dict[str, list[str]] = {
    "lovable": ["test_lovable_headers_and_version",
                "test_lovable_publish_project",
                "test_lovable_plan_gate_translated"],
    "replit": ["test_replit_bearer_auth_and_paths",
               "test_replit_set_budget_write_action",
               "test_replit_enterprise_gate_translated"],
}


def _test_functions() -> set[str]:
    found: set[str] = set()
    for path in (RUNTIME / "tests").glob("test_*.py"):
        text = path.read_text(encoding="utf-8")
        found.update(re.findall(r"^def (test_\w+)\(", text, re.M))
        found.update(re.findall(r"^async def (test_\w+)\(", text, re.M))
    return found


def _mock_contract_skills() -> set[str]:
    skills: set[str] = set()
    for path in (RUNTIME / "tests").glob("test_*.py"):
        text = path.read_text(encoding="utf-8")
        skills.update(
            re.findall(r"mock_harness\.register\(\s*[\"']([\w-]+)[\"']",
                       text))
    return skills


def build_matrix() -> list[tuple[str, str, str]]:
    """Return [(skill, tier, evidence)] for every implemented driver."""
    sys.path.insert(0, str(RUNTIME))
    from skillhub.registry import load_registry
    reg = load_registry()

    test_fns = _test_functions()
    for skill, fn in LIVE_TESTS.items():
        assert fn in test_fns, \
            f"live test {fn} for skill '{skill}' is gone — tier is stale"
    for skill, fns in MOCK_CONTRACT_TESTS.items():
        for fn in fns:
            assert fn in test_fns, \
                f"contract test {fn} for skill '{skill}' is gone — tier is stale"
    mock_skills = _mock_contract_skills() | set(MOCK_CONTRACT_TESTS)

    rows = []
    for name in sorted(reg):
        entry = reg[name]
        if not entry.implemented:
            continue
        if name in LIVE_TESTS:
            evidence = f"{LIVE_TESTS[name]} hits the provider's servers"
            if name in mock_skills:
                evidence += " + mock-harness contract test"
            rows.append((name, "live", evidence))
        elif name in mock_skills:
            if name in MOCK_CONTRACT_TESTS:
                evidence = ("mocked transport asserts request shape + "
                            "response parsing (no provider contact)")
            else:
                evidence = ("mock-harness responder asserts request shape + "
                            "response parsing")
            rows.append((name, "mock-contract", evidence))
        else:
            rows.append((name, "structural",
                         "schema/dispatch/unit tests only — no provider "
                         "contact"))
    return rows


def render(rows: list[tuple[str, str, str]]) -> str:
    from collections import Counter
    counts = Counter(tier for _, tier, _ in rows)
    lines = [
        "<!-- MATRIX:START -->",
        "_Generated by `runtime/tools/provider_matrix.py` — do not hand-edit._",
        "",
        f"**{len(rows)} implemented drivers**: "
        f"{counts['live']} live · "
        f"{counts['mock-contract']} mock-contract · "
        f"{counts['structural']} structural.",
        "",
        "**Evidence tiers**: `live` = a test performs a real network call to "
        "the provider's servers; `mock-contract` = a mock-harness responder "
        "or mocked transport asserts the driver's request shape and response "
        "parsing with the real driver code unmodified; `structural` = "
        "schema/dispatch/unit tests only — the driver has never contacted a "
        "provider server in this repo's test suite. Structural drivers are "
        "honest about what they are: the code is real, the provider handshake "
        "is the operator's step (credentials + network).",
        "",
        "| skill | tier | evidence |",
        "|---|---|---|",
    ]
    for name, tier, evidence in rows:
        lines.append(f"| `{name}` | {tier} | {evidence} |")
    lines.append("<!-- MATRIX:END -->")
    return "\n".join(lines) + "\n"


def main() -> int:
    check = "--check" in sys.argv
    rows = build_matrix()
    text = render(rows)
    MATRIX_PATH.parent.mkdir(parents=True, exist_ok=True)
    if check:
        current = MATRIX_PATH.read_text(encoding="utf-8") \
            if MATRIX_PATH.exists() else ""
        if current != text:
            print("OUT OF SYNC: run python tools/provider_matrix.py")
            return 1
        print("provider matrix in sync")
        return 0
    MATRIX_PATH.write_text(text, encoding="utf-8")
    print(f"wrote {MATRIX_PATH} ({len(rows)} drivers)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
